apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8slon-ing
  namespace: k8slon
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8slon.vpetersson.com
    http:
      paths:
        - path: /
          backend:
            serviceName: k8slon-service
            servicePort: 80
